compressor: main.c hashcomp.c hashmap.c slowcomp.c slowdict.c treecomp.c treedict.c listfunc.c timer.c
	gcc -o compressor main.c hashcomp.c hashmap.c slowcomp.c slowdict.c treecomp.c treedict.c listfunc.c timer.c -I.

clean:
	\rm -f *.o compressor *~ *#